[project]
name = "agentic-werewolf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.5.0",
    "smolagents[toolkit]>=1.23.0",
    "textual>=6.8.0",
    "textual-dev>=1.8.0",
]
